sudo: required
language: python
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.16.1
before_install:
- openssl aes-256-cbc -K $encrypted_1f39af138ba1_key -iv $encrypted_1f39af138ba1_iv
  -in id_rsa.enc -out id_rsa -d
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
before_script:
- bash _scripts/install.sh
script:
- docker-compose run questmaker python manage.py test
after_success:
- bash _scripts/deploy.sh
