sudo: required
language: python
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.16.1
addons:
  ssh_known_hosts: 159.65.124.54
before_script:
- bash _scripts/install.sh
script:
- docker-compose up --build -d
- docker-compose run questmaker python manage.py test
- docker-compose run questmaker python manage.py recreate_db
- docker-compose run questmaker python manage.py seed_db
after_success:
- bash _scripts/deploy.sh
