sudo: required
language: python
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.16.1
before_script:
- bash _scripts/install.sh
script:
- docker-compose run questmaker python manage.py test
after_success:
- bash _scripts/deploy.sh
