version: '2.1'

services:

  db:
    container_name: db
    build: ./services/questmaker/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
    restart: always

  questmaker:
    container_name: questmaker
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=services.questmaker.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/questmaker_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/questmaker_test
      - HOST_IP=${HOST_IP}
      - SECRET_KEY=my_precious
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: always

volumes:
  .:


  # nginx:
  #   container_name: nginx
  #   build: ./services/nginx/
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     questmaker:
  #       condition: service_started
  #   links:
  #     - questmaker
  #   restart: always

  # newman:
  #   image: postman/newman_ubuntu1404
  #   container_name: newman
  #   command: run /postman/ankete_collection.json -e /postman/ankete_environment.json
  #   depends_on:
  #     - questmaker
  #     #- migrate
  #   volumes:
  #     - ./postman:/postman
  #   restart: on-failure
