version: '2.1'

services:

  questmaker-db:
    container_name: questmaker-db
    build: ./services/questmaker/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  questmaker:
    container_name: questmaker
    build: .
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=services.questmaker.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@questmaker-db:5432/questmaker_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@questmaker-db:5432/questmaker_test
      - SECRET_KEY=my_precious
    depends_on:
      questmaker-db:
        condition: service_healthy
    links:
      - questmaker-db

  mongo-db:
    image: mongo:3.0.2
    healthcheck:
      test: exit 0

  resultkeeper:
    container_name: resultkeeper
    build:
      context:
        ./services/resultkeeper
    ports:
      - 5002:5000 # expose ports - HOST:CONTAINER
    depends_on:
      mongo-db:
        condition: service_healthy
      questmaker:
        condition: service_started
    links:
      - mongo-db
      - questmaker


  nginx:
    container_name: nginx
    build: ./services/nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      questmaker:
        condition: service_started
    links:
      - questmaker

  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:      
      - API_URL=https://raw.githubusercontent.com/GrailFinder/questionnaire/dev/services/swagger/swagger.json
    depends_on:
      questmaker:
        condition: service_started

  rabbit:
    container_name: nameko-example-rabbitmq
    image: rabbitmq:3.6-management
    ports:
        - "15672:15672"
    restart: always